export default interface SchemeModel {
    name: boolean;
    type: boolean;
    classId: boolean;
    gender: boolean;
    raceId: boolean;
    level: boolean;
    strength: boolean;
    dexterity: boolean;
    intelligence: boolean;
    constitution: boolean;
    wisdom: boolean;
    charisma: boolean;
    armorClass: boolean;
    fortitude: boolean;
    reflex: boolean;
    will: boolean;
    baseAttackBonus: boolean;
    spellResistance: boolean;
    size: boolean | null;
    maxHp: boolean;
    currentHp: boolean;
    speed: boolean;
    hair: boolean;
    eyes: boolean;
    fly: boolean;
    swim: boolean;
    climb: boolean;
    burrow: boolean;
    touch: boolean;
    flatFooted: boolean;
    homeland: boolean;
    deity: boolean;
    height: boolean;
    weight: boolean;
    experience: boolean;
    age: boolean;
}